spring.application.name=WEB-Java
feature.toggles.cosmoCats=true
feature.toggles.kittyProducts=false

spring.datasource.url=jdbc:postgresql://dpg-d4utnvmmcj7s73dbs270-a.virginia-postgres.render.com:5432/cosmocat?sslmode=require
spring.datasource.username=user
spring.datasource.password=xcYK2VFE6S6eV2V7XXJQ8IZKUGkWtBcH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dummy-auth-server.com
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
